common:
  namespace: mateapp

todoapp:
  secrets:
    SECRET_KEY: "1234"
    DB_NAME: app_db
    DB_USER: app_user
    DB_PASSWORD: "1234"
    DB_HOST: mysql-0.mysql.mysql.svc.cluster.local

  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  image:
    repository: klemjl/todoapp
    version: "metrics"

  affinity:
    weight: 1
    key: app
    operator: In
    values:
    - todoapp

  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpu:
      averageUtilization: 70
    memory:
      averageUtilization: 70

  pv:
    storage: 1Gi

  pvc:
    storage: 1Gi

  rbac:
    ServiceAccount: secrets-reader

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
  interval: 10s
  path: /metrics
  port: http
